export const FETCH_PURCHASE_ITEMS_REQUEST = "FETCH_PURCHASE_ITEMS_REQUEST";
export const FETCH_PURCHASE_ITEMS_SUCCESS = "FETCH_PURCHASE_ITEMS_SUCCESS";
export const FETCH_PURCHASE_ITEMS_FAILURE = "FETCH_PURCHASE_ITEMS_FAILURE";

export const FETCH_PURCHASE_DISTRIBUTER_REQUEST = "FETCH_PURCHASE_DISTRIBUTER_REQUEST";
export const FETCH_PURCHASE_DISTRIBUTER_SUCCESS = "FETCH_PURCHASE_DISTRIBUTER_SUCCESS";
export const FETCH_PURCHASE_DISTRIBUTER_FAILURE = "FETCH_PURCHASE_DISTRIBUTER_FAILURE";