// for doctor 
export const FETCH_DOCTOR_REQUEST = "FETCH_DOCTOR_REQUEST";
export const FETCH_DOCTOR_SUCCESS = "FETCH_DOCTOR_SUCCESS";
export const FETCH_DOCTOR_FAILURE = "FETCH_DOCTOR_FAILURE";
// for customer 
export const FETCH_CUSTOMER_REQUEST = "FETCH_CUSTOMER_REQUEST";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_FAILURE = "FETCH_CUSTOMER_FAILURE";

// for sales 
export const FETCH_SALES_ITEM_REQUEST = "FETCH_SALES_ITEM_REQUEST";
export const FETCH_SALES_ITEM_SUCCESS = "FETCH_SALES_ITEM_SUCCESS";
export const FETCH_SALES_ITEM_FAILURE = "FETCH_SALES_ITEM_FAILURE";
// for purchase 
export const FETCH_PURCHASE_ITEMS_REQUEST = "FETCH_PURCHASE_ITEMS_REQUEST";
export const FETCH_PURCHASE_ITEMS_SUCCESS = "FETCH_PURCHASE_ITEMS_SUCCESS";
export const FETCH_PURCHASE_ITEMS_FAILURE = "FETCH_PURCHASE_ITEMS_FAILURE";
// for purchase return 
export const FETCH_PURCHASE_DISTRIBUTER_REQUEST = "FETCH_PURCHASE_DISTRIBUTER_REQUEST";
export const FETCH_PURCHASE_DISTRIBUTER_SUCCESS = "FETCH_PURCHASE_DISTRIBUTER_SUCCESS";
export const FETCH_PURCHASE_DISTRIBUTER_FAILURE = "FETCH_PURCHASE_DISTRIBUTER_FAILURE";